### ISSUE TITLE
取消chrome记住密码提示

### ISSUE THREAD

**Issue by zzzplus** [zzzplus/blog#72]
规则：跳转的页面如果有type="password"，就不会显示提示
```html
  form.form-field-group.form-hidden
    input.form-field.form-field-hidden(type="password")
```
```css
.form-hidden,
.form-field-hidden {
  margin: 0;
  padding: 0;
  height: 0;
  width: 0;
  opacity: 0;
}
```
[参考网址](https://www.ucloud.cn/yun/50055.html)
